/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Dominio.Producto;
import Dominio.TipoProducto;
import exception.NegocioException;
import interfaces.IProductosBO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author payde
 */
public class BuscadorProductosComandas extends javax.swing.JPanel {
    private IProductosBO productosBO;
    private SeleccionarProductosComanda seleccionarProductosComanda;
    
    /**
     * Creates new form BuscadorProductosEnComandas
     */
    

    public BuscadorProductosComandas(IProductosBO productosBO, SeleccionarProductosComanda seleccionarProductosComanda) {
        this.productosBO = productosBO;
        this.seleccionarProductosComanda = seleccionarProductosComanda;
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscarProducto = new javax.swing.JButton();
        jTextFieldIngresarProducto = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(260, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBuscarProducto.setBorderPainted(false);
        jButtonBuscarProducto.setContentAreaFilled(false);
        jButtonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProductoActionPerformed(evt);
            }
        });
        add(jButtonBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 30, 40));

        jTextFieldIngresarProducto.setText("Productos...");
        jTextFieldIngresarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldIngresarProductoMousePressed(evt);
            }
        });
        jTextFieldIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresarProductoActionPerformed(evt);
            }
        });
        add(jTextFieldIngresarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 240, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProductoActionPerformed
        String texto = jTextFieldIngresarProducto.getText().trim().toLowerCase();
        
        try {
            List<Producto> resultados;

            switch (texto) {
                case "platillo":
                    resultados = productosBO.obtenerProductoPorTipo(TipoProducto.PLATILLO);
                    break;
                case "bebida":
                    resultados = productosBO.obtenerProductoPorTipo(TipoProducto.BEBIDA);
                    break;
                case "postre":
                    resultados = productosBO.obtenerProductoPorTipo(TipoProducto.POSTRE);
                    break;
                default:
                    resultados = productosBO.buscarPorNombre(texto);
                    break;
            }
            //seleccionarProductosComanda.mostrarResultados(resultados);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar productos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarProductoActionPerformed

    private void jTextFieldIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngresarProductoActionPerformed

    private void jTextFieldIngresarProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIngresarProductoMousePressed
        if (jTextFieldIngresarProducto.getText().equals("Productos...")) {
            jTextFieldIngresarProducto.setText("");
        }
    }//GEN-LAST:event_jTextFieldIngresarProductoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarProducto;
    private javax.swing.JTextField jTextFieldIngresarProducto;
    // End of variables declaration//GEN-END:variables
}
