/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Dominio.Comanda;
import Dominio.EstadoComanda;
import Dominio.EstadoMesa;
import Dominio.Ingrediente;
import Dominio.Mesa;
import GUI.ControlPresentacion.ControlPresentacion;
import dto.ComandaDTO;
import dto.NuevaComandaDTO;
import dto.NuevoIngredienteDTO;
import dto.ProductoSeleccionadoDTO;
import exception.NegocioException;
import interfaces.IComandasBO;
import interfaces.IIngredientesBO;
import interfaces.IMesasBO;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author riosr
 */
public class ConfirmacionInicioComandanda extends javax.swing.JPanel {

    private IComandasBO comandasBO;
    private IMesasBO mesasBO;
    private static final Logger LOG = Logger.getLogger(ConfirmacionInicioComandanda.class.getName());
    private List<ProductoSeleccionadoDTO> productosSeleccionados;
    FontManager fontManager = new FontManager();
    ControlPresentacion control;
    VentanaInicioComanda ventanaInicioComanda;
    Mesa mesa;
    

    /**
     * Creates new form ConfirmacionInicioComanda
     */
    public ConfirmacionInicioComandanda() {
        initComponents();
    }

    public ConfirmacionInicioComandanda(ControlPresentacion control, Mesa mesa, VentanaInicioComanda ventanaInicioComanda, IComandasBO comandasBO, IMesasBO mesasBO) {
        this.control = control;
        this.mesa = mesa;
        this.mesasBO = mesasBO;
        this.ventanaInicioComanda = ventanaInicioComanda;
        this.comandasBO = comandasBO; 
        initComponents();
        setOpaque(false);
        String nuevoTexto = "<html><div style='text-align: center;'>¿Estás seguro de iniciar<br>una nueva comanda para la <br>mesa " 
                + mesa.getNumeroMesa() + "?</div></html>";
        this.jLabelMensaje.setText(nuevoTexto);
    }
      
    public void registrarComanda(){        
        NuevaComandaDTO nuevaComanda = new NuevaComandaDTO(EstadoComanda.ABIERTA, mesa);

        try {
            Comanda comandaCreada = this.comandasBO.crearNuevaComanda(nuevaComanda);
            
            mesasBO.cambiarEstadoMesa(mesa.getId(), EstadoMesa.RESERVADA);

            if (comandaCreada.getId() == null) {
                JOptionPane.showMessageDialog(this, "No se generó el ID de la comanda", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Se inició la nueva comanda con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);

            ComandaDTO comandaDTO = new ComandaDTO();
            comandaDTO.setFechaHoraCreacion(Calendar.getInstance());
            comandaDTO.setId(comandaCreada.getId());
            comandaDTO.setEstadoComanda(comandaCreada.getEstadoComanda());
            comandaDTO.setFolio(comandaCreada.getFolio());
            comandaDTO.setMesa(comandaCreada.getMesa());
            comandaDTO.setCliente(comandaCreada.getCliente());
            
            boolean esComandaNueva = true;

            control.mostrarSeleccionarProductosComanda(mesa, comandaDTO, esComandaNueva, productosSeleccionados);

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            LOG.severe("No fue posible iniciar una nueva comanda: " + ex.getMessage());
        }     
    }

    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jLabelMensaje = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(124, 184, 245));

        jButtonCerrarSesion.setBackground(new java.awt.Color(255, 122, 122));
        jButtonCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButtonCerrarSesion.setText("Salir");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonReportes.setBackground(new java.awt.Color(0, 153, 255));
        jButtonReportes.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jButtonReportes.setText("Confirmar");
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });

        jLabelMensaje.setFont(fontManager.getNunitoSemiBold(28f));
        jLabelMensaje.setText("¿Estás seguro de iniciar una nueva comanda para la mesa 1?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButtonCerrarSesion)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonReportes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrarSesion)
                    .addComponent(jButtonReportes))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        registrarComanda();
        cerrar();
        ventanaInicioComanda.cerrar();
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonReportes;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
