/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Dominio.Producto;
import Dominio.TipoProducto;
import GUI.ControlPresentacion.ControlPresentacion;
import dto.IngredienteProductoDTO;
import dto.NuevoProductoDTO;
import exception.NegocioException;
import interfaces.IIngredientesBO;
import interfaces.IIngredientesProductosBO;
import interfaces.IProductosBO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author riosr
 */
public class EditarProducto extends javax.swing.JPanel {

    private IIngredientesBO ingredientesBO;
    private IIngredientesProductosBO ingredientesProductosBO;
    private ControlPresentacion control;
    private IProductosBO productosBO;
    private Producto producto; 
    private TipoProducto tipoProducto;
    private List<IngredienteProductoDTO> ingredientesSeleccionados = new ArrayList<>();
    /**
     * Creates new form NuevoProducto
     */
    public EditarProducto() {
        initComponents();
    }

    public EditarProducto(ControlPresentacion control, IProductosBO productosBO,
        IIngredientesBO ingredientesBO, IIngredientesProductosBO ingredientesProductosBO,
        Producto producto) {
        this.control = control;
        this.productosBO = productosBO;
        this.ingredientesBO = ingredientesBO;
        this.ingredientesProductosBO = ingredientesProductosBO;
        this.producto = producto;
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosProducto();

        try {
            List<IngredienteProductoDTO> ingredientes = ingredientesProductosBO.buscarPorProducto(producto.getId());
            mostrarIngredientesSeleccionados(ingredientes);
        } catch (NegocioException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar ingredientes del producto.");
        }
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    private void cargarDatosProducto() {
        lblTitulo.setText(producto.getNombre()); 
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextFieldNombreProducto.setText(producto.getNombre());
        jTextFieldNombrePrecio.setText(String.valueOf(producto.getPrecio()));
        jComboBoxCategoria.setSelectedItem(producto.getTipoProducto().toString()); 
    }
   
    private void guardarCambiosProducto() {
        try {
            String nombre = jTextFieldNombreProducto.getText().trim();
            String precioStr = jTextFieldNombrePrecio.getText().trim().replace("$", "").trim();
            String tipoSeleccionado = jComboBoxCategoria.getSelectedItem().toString().toUpperCase();

            float precio = Float.parseFloat(precioStr);

            NuevoProductoDTO productoDTO = new NuevoProductoDTO();
            productoDTO.setId(producto.getId()); 
            productoDTO.setNombre(nombre);
            productoDTO.setPrecio(precio);
            productoDTO.setTipoProducto(TipoProducto.valueOf(tipoSeleccionado)); 

            productosBO.editarProducto(productoDTO);

            javax.swing.JOptionPane.showMessageDialog(this, "Producto actualizado con éxito");

        }catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar el producto: " + ex.getMessage());
        }
    }
    
    public void mostrarIngredientesSeleccionados(List<IngredienteProductoDTO> nuevos) {
        JPanel panelVisual = new JPanel();
        panelVisual.setLayout(new BoxLayout(panelVisual, BoxLayout.Y_AXIS));
        panelVisual.setOpaque(false);

        for (IngredienteProductoDTO ingredienteProductoDTO : nuevos) {
            String nombre = ingredienteProductoDTO.getIngrediente().getNombre();
            float cantidad = ingredienteProductoDTO.getCantidad();
            String unidad = ingredienteProductoDTO.getIngrediente().getUnidadMedida().toString();

            panelVisual.add(new IngredienteVisualPanel(nombre, cantidad, unidad));
        }

        jScrollPane1.setViewportView(panelVisual);
        panelVisual.revalidate();
        panelVisual.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldNombreProducto = new javax.swing.JTextField();
        jTextFieldNombrePrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEditarIngredientes = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(124, 184, 245));

        jTextFieldNombreProducto.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jTextFieldNombreProducto.setText("Nombre");
        jTextFieldNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreProductoActionPerformed(evt);
            }
        });

        jTextFieldNombrePrecio.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jTextFieldNombrePrecio.setText("Precio");
        jTextFieldNombrePrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePrecioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        jLabel1.setText("Editar Producto");

        jComboBoxCategoria.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platillo", "Postre", "Bebida" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del Producto");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel3.setText("Categoría");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setText("Precio");

        jButtonGuardar.setBackground(new java.awt.Color(124, 245, 143));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonEditarIngredientes.setBackground(new java.awt.Color(152, 168, 185));
        jButtonEditarIngredientes.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButtonEditarIngredientes.setText("Editar Ingredientes");
        jButtonEditarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarIngredientesActionPerformed(evt);
            }
        });

        jButtonRegresar.setBackground(new java.awt.Color(245, 124, 124));
        jButtonRegresar.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreProducto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombrePrecio))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEditarIngredientes)))
                        .addContainerGap(26, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEditarIngredientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombrePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonRegresar)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombrePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePrecioActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        cerrar();
        control.mostrarListaProductos();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jTextFieldNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreProductoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        guardarCambiosProducto();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarIngredientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarIngredientes;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombrePrecio;
    private javax.swing.JTextField jTextFieldNombreProducto;
    // End of variables declaration//GEN-END:variables
}
