/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author riosr
 */
public class GUIMenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form GUIMenuPrincipal
     */
    public GUIMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuPrincipalEmpleados = new javax.swing.JButton();
        btnMenuPrincipalMesas = new javax.swing.JButton();
        btnMenuPrincipalClientes = new javax.swing.JButton();
        btnMenuPrincipalIngredientes = new javax.swing.JButton();
        btnMenuPrincipalComandas = new javax.swing.JButton();
        btnMenuPrincipalSalir = new javax.swing.JButton();
        btnMenuPrincipalProductos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(124, 184, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 48)); // NOI18N
        jLabel1.setText("Menú Principal");

        btnMenuPrincipalEmpleados.setBackground(new java.awt.Color(161, 173, 185));
        btnMenuPrincipalEmpleados.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnMenuPrincipalEmpleados.setText("Empleados");
        btnMenuPrincipalEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalEmpleadosActionPerformed(evt);
            }
        });

        btnMenuPrincipalMesas.setBackground(new java.awt.Color(161, 173, 185));
        btnMenuPrincipalMesas.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnMenuPrincipalMesas.setText("Mesas");

        btnMenuPrincipalClientes.setBackground(new java.awt.Color(161, 173, 185));
        btnMenuPrincipalClientes.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnMenuPrincipalClientes.setText("Clientes");

        btnMenuPrincipalIngredientes.setBackground(new java.awt.Color(161, 173, 185));
        btnMenuPrincipalIngredientes.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnMenuPrincipalIngredientes.setText("Ingredientes");

        btnMenuPrincipalComandas.setBackground(new java.awt.Color(161, 173, 185));
        btnMenuPrincipalComandas.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnMenuPrincipalComandas.setText("Comandas");

        btnMenuPrincipalSalir.setBackground(new java.awt.Color(255, 122, 122));
        btnMenuPrincipalSalir.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnMenuPrincipalSalir.setText("Salir");

        btnMenuPrincipalProductos.setBackground(new java.awt.Color(161, 173, 185));
        btnMenuPrincipalProductos.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnMenuPrincipalProductos.setText("Productos");
        btnMenuPrincipalProductos.setActionCommand("");
        btnMenuPrincipalProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 141, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnMenuPrincipalSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMenuPrincipalEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuPrincipalComandas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuPrincipalMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuPrincipalClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuPrincipalProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuPrincipalIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMenuPrincipalEmpleados)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPrincipalComandas)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPrincipalMesas)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPrincipalClientes)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPrincipalProductos)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPrincipalIngredientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnMenuPrincipalSalir)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuPrincipalEmpleadosActionPerformed

    private void btnMenuPrincipalProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuPrincipalProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuPrincipalClientes;
    private javax.swing.JButton btnMenuPrincipalComandas;
    private javax.swing.JButton btnMenuPrincipalEmpleados;
    private javax.swing.JButton btnMenuPrincipalIngredientes;
    private javax.swing.JButton btnMenuPrincipalMesas;
    private javax.swing.JButton btnMenuPrincipalProductos;
    private javax.swing.JButton btnMenuPrincipalSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
