/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author riosr
 */
public class GUIMenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form GUIMenuPrincipal
     */
    public GUIMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuPrincipalEmpleados = new javax.swing.JButton();
        MenuPrincipalMesas = new javax.swing.JButton();
        MenuPrincipalClientes = new javax.swing.JButton();
        MenuPrincipalIngredientes = new javax.swing.JButton();
        MenuPrincipalComandas = new javax.swing.JButton();
        MenuPrincipalSalir = new javax.swing.JButton();
        MenuPrincipalProductos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(124, 184, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 48)); // NOI18N
        jLabel1.setText("Menú Principal");

        MenuPrincipalEmpleados.setBackground(new java.awt.Color(161, 173, 185));
        MenuPrincipalEmpleados.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        MenuPrincipalEmpleados.setText("Empleados");
        MenuPrincipalEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalEmpleadosActionPerformed(evt);
            }
        });

        MenuPrincipalMesas.setBackground(new java.awt.Color(161, 173, 185));
        MenuPrincipalMesas.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        MenuPrincipalMesas.setText("Mesas");

        MenuPrincipalClientes.setBackground(new java.awt.Color(161, 173, 185));
        MenuPrincipalClientes.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        MenuPrincipalClientes.setText("Clientes");

        MenuPrincipalIngredientes.setBackground(new java.awt.Color(161, 173, 185));
        MenuPrincipalIngredientes.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        MenuPrincipalIngredientes.setText("Ingredientes");

        MenuPrincipalComandas.setBackground(new java.awt.Color(161, 173, 185));
        MenuPrincipalComandas.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        MenuPrincipalComandas.setText("Comandas");

        MenuPrincipalSalir.setBackground(new java.awt.Color(255, 122, 122));
        MenuPrincipalSalir.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        MenuPrincipalSalir.setText("Salir");

        MenuPrincipalProductos.setBackground(new java.awt.Color(161, 173, 185));
        MenuPrincipalProductos.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        MenuPrincipalProductos.setText("Productos");
        MenuPrincipalProductos.setActionCommand("");
        MenuPrincipalProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 144, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(MenuPrincipalSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MenuPrincipalEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPrincipalComandas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPrincipalMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPrincipalClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPrincipalProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPrincipalIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(MenuPrincipalEmpleados)
                .addGap(18, 18, 18)
                .addComponent(MenuPrincipalComandas)
                .addGap(18, 18, 18)
                .addComponent(MenuPrincipalMesas)
                .addGap(18, 18, 18)
                .addComponent(MenuPrincipalClientes)
                .addGap(18, 18, 18)
                .addComponent(MenuPrincipalProductos)
                .addGap(18, 18, 18)
                .addComponent(MenuPrincipalIngredientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(MenuPrincipalSalir)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPrincipalEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPrincipalEmpleadosActionPerformed

    private void MenuPrincipalProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPrincipalProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuPrincipalClientes;
    private javax.swing.JButton MenuPrincipalComandas;
    private javax.swing.JButton MenuPrincipalEmpleados;
    private javax.swing.JButton MenuPrincipalIngredientes;
    private javax.swing.JButton MenuPrincipalMesas;
    private javax.swing.JButton MenuPrincipalProductos;
    private javax.swing.JButton MenuPrincipalSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
