/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.ControlPresentacion.ControlPresentacion;
import dto.EmpleadoDTO;
import exception.NegocioException;
import interfaces.IEmpleadosBO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author riosr
 */
public class IniciarSesion extends javax.swing.JFrame {

    ControlPresentacion control;
    IEmpleadosBO empleadosBO;
    
    FontManager fontManager = new FontManager();
    
    /**
     * Creates new form GUIInicioSesion
     */
    public IniciarSesion() {
        initComponents();
    }

     public IniciarSesion(ControlPresentacion control, IEmpleadosBO empleadosBO) {
        this.control = control;
        this.empleadosBO = empleadosBO;
        initComponents();
        setLocationRelativeTo(null);
        
        jTextFieldUsuario.setOpaque(false);
        jPasswordField.setOpaque(false);
    }
     
     public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInicioSesionContinuar = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JTextField();
        btnInicioSesionContinuar1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(161, 173, 185));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 48)); // NOI18N
        jLabel1.setText("Inicio de Sesion");

        btnInicioSesionContinuar.setBackground(new java.awt.Color(124, 184, 245));
        btnInicioSesionContinuar.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnInicioSesionContinuar.setText("Continuar");
        btnInicioSesionContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionContinuarActionPerformed(evt);
            }
        });

        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnInicioSesionContinuar1.setBackground(new java.awt.Color(255, 122, 122));
        btnInicioSesionContinuar1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        btnInicioSesionContinuar1.setText("Salir");
        btnInicioSesionContinuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionContinuar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldUsuario)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addGap(250, 250, 250))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnInicioSesionContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInicioSesionContinuar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(302, 302, 302))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnInicioSesionContinuar)
                .addGap(41, 41, 41)
                .addComponent(btnInicioSesionContinuar1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionContinuarActionPerformed
        // TODO add your handling code here:
         String nombreUsuario = this.jTextFieldUsuario.getText();
        String contraseña = this.jPasswordField.getText();
        EmpleadoDTO empleado = new EmpleadoDTO();

        
        try {
            empleado = empleadosBO.iniciarSesion(nombreUsuario,contraseña);
        } catch (NegocioException ex) {
            Logger.getLogger(IniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (empleado != null) {
            control.iniciarFlujo(empleado.getIdRol());
            cerrar();
            
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo iniciar sesión. Verifica tu usuario y contraseña.", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInicioSesionContinuarActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void btnInicioSesionContinuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionContinuar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesionContinuar1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicioSesionContinuar;
    private javax.swing.JButton btnInicioSesionContinuar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
