/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Dominio.ClienteFrecuente;
import GUI.ControlPresentacion.ControlPresentacion;
import dto.ClienteFrecuenteDTO;
import exception.NegocioException;
import interfaces.IClientesBO;
import java.awt.BorderLayout;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author riosr
 */
public class ReportesClientes extends javax.swing.JPanel {

    private ControlPresentacion control;
    private IClientesBO clientesBO;
    
    FontManager fontManager = new FontManager();
    private static final Logger LOG = Logger.getLogger(ReportesClientes.class.getName());
    
    /**
     * Creates new form ReportesClientes
     */
    public ReportesClientes(ControlPresentacion control, IClientesBO clientesBO) {
        initComponents();
//        setLocationRelativeTo(null);
        this.clientesBO = clientesBO;
        this.control = control;
       
        
        agregarBuscador();
        mostrarInformacionClientes();
        
        jPanelBuscador.setOpaque(false);
        jScrollPaneListaClientes.setOpaque(false);
        jScrollPaneListaClientes.getViewport().setOpaque(false);
        jScrollPaneListaClientes.setBorder(null);

        
    }
    
    private void agregarBuscador() {
        BuscadorClientes buscadorClientes = new BuscadorClientes(clientesBO, this::actualizarListaClientes);
        jPanelBuscador.add(buscadorClientes, BorderLayout.CENTER);
    }
    
    private ClienteFrecuenteDTO crearClienteDTOConPuntos(ClienteFrecuente cliente) {
        ClienteFrecuenteDTO dto = new ClienteFrecuenteDTO(
            cliente.getId(),
            cliente.getNombre(),
            cliente.getApellidoPaterno(),
            cliente.getApellidoMaterno(),
            cliente.getCorreoElectronico(),
            cliente.getTelefono(),
            cliente.getFechaRegistro()
        );

        try {
            ClienteFrecuenteDTO datosFidelidad = clientesBO.obtenerDatosFidelidad(cliente.getId());
            dto.setVisitas(datosFidelidad.getVisitas());
            dto.setGastoTotal(datosFidelidad.getGastoTotal());
            dto.setPuntosFidelidad(datosFidelidad.getPuntosFidelidad());
        } catch (NegocioException ex) {
            dto.setPuntosFidelidad(0);
        }

        return dto;
    }
    
    private void actualizarListaClientes(List<ClienteFrecuente> clientes) {
        jPanelListaClientes.removeAll();
        for (ClienteFrecuente cliente : clientes) {

            ClienteFrecuenteDTO clienteDTO = crearClienteDTOConPuntos(cliente);

            PanelReporteCliente panel = new PanelReporteCliente(
                clienteDTO, 
                "Ver",
                e -> control.mostrarDetalleReporteCliente(cliente, clienteDTO)
            );
            panel.actualizarPuntos(clienteDTO.getPuntosFidelidad()); 
            jPanelListaClientes.add(panel);
        }
        jPanelListaClientes.revalidate();
        jPanelListaClientes.repaint();
    }

    public void mostrarInformacionClientes() {
        jPanelListaClientes.removeAll(); 
        try {
            for (ClienteFrecuente cliente : clientesBO.obtenerClientes()) {
                
                ClienteFrecuenteDTO clienteDTO = crearClienteDTOConPuntos(cliente);

                PanelReporteCliente panel = new PanelReporteCliente(
                    clienteDTO, 
                    "Ver",
                    e -> control.mostrarDetalleReporteCliente(cliente, clienteDTO)
                );

                panel.actualizarPuntos(clienteDTO.getPuntosFidelidad());

                jPanelListaClientes.add(panel);
            }
        } catch (NegocioException ex) {
            LOG.severe("No se pudo llenar la lista de clientes: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error al cargar clientes: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }

        jPanelListaClientes.revalidate();
        jPanelListaClientes.repaint();
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
//        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jScrollPaneListaClientes = new javax.swing.JScrollPane();
        jPanelListaClientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(124, 184, 245));

        jPanelBuscador.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jPanelBuscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanelBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelBuscadorMousePressed(evt);
            }
        });
        jPanelBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPanelBuscadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 40)); // NOI18N
        jLabel1.setText("Reportes Clientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("Visitas");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jButtonVolver.setBackground(new java.awt.Color(245, 124, 124));
        jButtonVolver.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButtonVolver.setText("Regresar");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jScrollPaneListaClientes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelListaClientes.setBackground(new java.awt.Color(204, 204, 204));
        jPanelListaClientes.setLayout(new javax.swing.BoxLayout(jPanelListaClientes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneListaClientes.setViewportView(jPanelListaClientes);

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setText("Puntos");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setText("Ver");

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel6.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel2)
                                .addGap(142, 142, 142)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPaneListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPanelBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(jButtonVolver)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelBuscadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBuscadorMousePressed
        // TODO add your handling code here:
       // if(jPanelBuscador.getText().equals("Nombre")){
         //   jPanelBuscador.setText("");
        //}
        //if(jTextFieldCantidad.getText().isEmpty()){
          //  jTextFieldCantidad.setText("0");
        //}
    }//GEN-LAST:event_jPanelBuscadorMousePressed

    private void jPanelBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPanelBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelBuscadorActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        control.mostrarIniciarReporte();
        cerrar();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPanelBuscador;
    private javax.swing.JPanel jPanelListaClientes;
    private javax.swing.JScrollPane jScrollPaneListaClientes;
    // End of variables declaration//GEN-END:variables
}
