/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Dominio.ClienteFrecuente;
import Dominio.Mesa;
import GUI.ControlPresentacion.ControlPresentacion;
import dto.ClienteFrecuenteDTO;
import dto.NuevaMesaDTO;
import exception.NegocioException;
import interfaces.IClientesBO;
import interfaces.IMesasBO;
import java.awt.BorderLayout;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author riosr
 */
public class ReportesClientes extends javax.swing.JPanel {

     private ControlPresentacion control;
    private IClientesBO clientesBO;
    
    FontManager fontManager = new FontManager();
    private static final Logger LOG = Logger.getLogger(ReportesClientes.class.getName());
    
    /**
     * Creates new form ReportesClientes
     */
    public ReportesClientes(ControlPresentacion control, IClientesBO clientesBO) {
        initComponents();
//        setLocationRelativeTo(null);
        this.clientesBO = clientesBO;
        this.control = control;
       
        
        agregarBuscador();
        mostrarInformacionClientes();
        
        jPanelBuscador.setOpaque(false);
        jScrollPaneListaClientes.setOpaque(false);
        jScrollPaneListaClientes.getViewport().setOpaque(false);
        jScrollPaneListaClientes.setBorder(null);

        
    }
    
    private void agregarBuscador() {
        BuscadorClientes buscadorClientes = new BuscadorClientes(clientesBO, this::actualizarListaClientes);
        jPanelBuscador.add(buscadorClientes, BorderLayout.CENTER);
    }
    
    private ClienteFrecuenteDTO crearClienteDTOConPuntos(ClienteFrecuente cliente) {
        ClienteFrecuenteDTO dto = new ClienteFrecuenteDTO(
            cliente.getId(),
            cliente.getNombre(),
            cliente.getApellidoPaterno(),
            cliente.getApellidoMaterno(),
            cliente.getCorreoElectronico(),
            cliente.getTelefono(),
            cliente.getFechaRegistro()
        );

        try {
            ClienteFrecuenteDTO datosFidelidad = clientesBO.obtenerDatosFidelidad(cliente.getId());
            dto.setVisitas(datosFidelidad.getVisitas());
            dto.setGastoTotal(datosFidelidad.getGastoTotal());
            dto.setPuntosFidelidad(datosFidelidad.getPuntosFidelidad());
        } catch (NegocioException ex) {
            dto.setPuntosFidelidad(0);
        }

        return dto;
    }
    
    private void actualizarListaClientes(List<ClienteFrecuente> clientes) {
        jPanelListaClientes.removeAll();
        for (ClienteFrecuente cliente : clientes) {

            ClienteFrecuenteDTO clienteDTO = crearClienteDTOConPuntos(cliente);

            PanelReporteCliente panel = new PanelReporteCliente(
                clienteDTO, 
                "Ver",
                e -> control.mostrarDetalleReporteCliente(cliente, clienteDTO)
            );
            panel.actualizarPuntos(clienteDTO.getPuntosFidelidad()); 
            jPanelListaClientes.add(panel);
        }
        jPanelListaClientes.revalidate();
        jPanelListaClientes.repaint();
    }

    public void mostrarInformacionClientes() {
        jPanelListaClientes.removeAll(); 
        try {
            for (ClienteFrecuente cliente : clientesBO.obtenerClientes()) {
                
                ClienteFrecuenteDTO clienteDTO = crearClienteDTOConPuntos(cliente);

                PanelReporteCliente panel = new PanelReporteCliente(
                    clienteDTO, 
                    "Ver",
                    e -> control.mostrarDetalleReporteCliente(cliente, clienteDTO)
                );

                panel.actualizarPuntos(clienteDTO.getPuntosFidelidad());

                jPanelListaClientes.add(panel);
            }
        } catch (NegocioException ex) {
            LOG.severe("No se pudo llenar la lista de clientes: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error al cargar clientes: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }

        jPanelListaClientes.revalidate();
        jPanelListaClientes.repaint();
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
//        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMesasRegresar = new javax.swing.JButton();
        btnMesasRegresar1 = new javax.swing.JButton();
        jPanelBuscador = new javax.swing.JPanel();
        jLabelPuntos = new javax.swing.JLabel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jScrollPaneListaClientes = new javax.swing.JScrollPane();
        jPanelListaClientes = new javax.swing.JPanel();
        jLabelVisitas = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(124, 184, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 48)); // NOI18N
        jLabel1.setText("Mesas");

        btnMesasRegresar.setBackground(new java.awt.Color(255, 122, 122));
        btnMesasRegresar.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnMesasRegresar.setText("Regresar");
        btnMesasRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasRegresarActionPerformed(evt);
            }
        });

        btnMesasRegresar1.setBackground(new java.awt.Color(153, 255, 153));
        btnMesasRegresar1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnMesasRegresar1.setText("Agregar");
        btnMesasRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasRegresar1ActionPerformed(evt);
            }
        });

        jPanelBuscador.setLayout(new javax.swing.BoxLayout(jPanelBuscador, javax.swing.BoxLayout.LINE_AXIS));

        jLabelPuntos.setFont(fontManager.getNotoSerifCondensedRegular(26f)
        );
        jLabelPuntos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPuntos.setText("Puntos");

        jLabelNombreCliente.setFont(fontManager.getNotoSerifCondensedRegular(26f)
        );
        jLabelNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreCliente.setText("Nombre Completo");

        jScrollPaneListaClientes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelListaClientes.setBackground(new java.awt.Color(204, 204, 204));
        jPanelListaClientes.setLayout(new javax.swing.BoxLayout(jPanelListaClientes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneListaClientes.setViewportView(jPanelListaClientes);

        jLabelVisitas.setFont(fontManager.getNotoSerifCondensedRegular(26f)
        );
        jLabelVisitas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVisitas.setText("Visitas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                                .addComponent(jPanelBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMesasRegresar)
                                .addGap(501, 501, 501)
                                .addComponent(btnMesasRegresar1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelNombreCliente)
                        .addGap(84, 84, 84)
                        .addComponent(jLabelVisitas)
                        .addGap(99, 99, 99)
                        .addComponent(jLabelPuntos)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanelBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btnMesasRegresar1)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreCliente)
                            .addComponent(jLabelVisitas)
                            .addComponent(jLabelPuntos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMesasRegresar)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMesasRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasRegresarActionPerformed
        // TODO add your handling code here:
        control.mostrarIniciarReporte();
        cerrar();
    }//GEN-LAST:event_btnMesasRegresarActionPerformed

    private void btnMesasRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasRegresar1ActionPerformed
        // TODO add your handling code here:

      
    }//GEN-LAST:event_btnMesasRegresar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMesasRegresar;
    private javax.swing.JButton btnMesasRegresar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelPuntos;
    private javax.swing.JLabel jLabelVisitas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBuscador;
    private javax.swing.JPanel jPanelListaClientes;
    private javax.swing.JScrollPane jScrollPaneListaClientes;
    // End of variables declaration//GEN-END:variables
}
